SBMS/Controllers/CustomerController.cs
using SBMS.Models;
using System.Linq;
using System.Web.Mvc;

namespace SBMS.Controllers
{
    public class CustomerController : Controller
    {
        private readonly SBMSDbContext _db = new SBMSDbContext();

        // GET: /Customer/

        public ActionResult Index()
        {
            return View(_db.Customers.ToList());
        }

        // GET: /Customer/Details/5

        //public ActionResult Details(int id = 0)
        //{
        //    Customer customer = _db.Customers.Find(id);
        //    if (customer == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(customer);
        //}

        // GET: /Customer/Create

        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: /Customer/Create

        //[HttpPost]
        //public ActionResult Create(Customer customer)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _db.Customers.Add(customer);
        //        _db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(customer);
        //}

        // GET: /Customer/Edit/5

        //public ActionResult Edit(int id = 0)
        //{
        //    Customer customer = _db.Customers.Find(id);
        //    if (customer == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(customer);
        //}

        // POST: /Customer/Edit/5

        //[HttpPost]
        //public ActionResult Edit(Customer customer)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _db.Entry(customer).State = EntityState.Modified;
        //        _db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(customer);
        //}

        // GET: /Customer/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Customer customer = _db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: /Customer/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = _db.Customers.Find(id);
            _db.Customers.Remove(customer);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SBMS/Controllers/HomeController.cs
using System.Web.Mvc;

namespace SBMS.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult About()
        {
            ViewBag.Message = "Know more about who we are and what we do.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Get in touch with us.";

            return View();
        }

        public ActionResult EmployeeLanding()
        {
            return View();
        }
    }
}

SBMS/Controllers/ProjectController.cs
using SBMS.Models;
using System.Linq;
using System.Web.Mvc;

namespace SBMS.Controllers
{
    public class ProjectController : Controller
    {
        private readonly SBMSDbContext _db = new SBMSDbContext();
        private readonly DetailsForCustomerViewModel _detailsForCustViewModel = new DetailsForCustomerViewModel();

        // GET: /Project/

        public ActionResult Index()
        {
            return View(_db.Projects.ToList());
        }

        // GET: /Project/Details/5

        //public ActionResult Details(int id = 0)
        //{
        //    Project project = _db.Projects.Find(id);
        //    if (project == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(project);
        //}

        // GET: /Project/Create

        //public ActionResult Create()
        //{
        //    return View();
        //}

        // POST: /Project/Create

        //[HttpPost]
        //public ActionResult Create(Project project)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _db.Projects.Add(project);
        //        _db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(project);
        //}

        // GET: /Project/Edit/5

        //public ActionResult Edit(int id = 0)
        //{
        //    Project project = _db.Projects.Find(id);
        //    if (project == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(project);
        //}

        // POST: /Project/Edit/5

        //[HttpPost]
        //public ActionResult Edit(Project project)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _db.Entry(project).State = EntityState.Modified;
        //        _db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(project);
        //}

        // GET: /Project/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Project project = _db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: /Project/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = _db.Projects.Find(id);
            _db.Projects.Remove(project);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult DetailsForCustomerView()
        {
            _detailsForCustViewModel.PopulateFromDbContext(_db);
            return View(_detailsForCustViewModel);
        }
    }
}

SBMS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
</hgroup>

<article>
    <section>
        <hgroup>
            <h3>Our goal</h3>
        </hgroup>
        <p>
            We build software applications that make your computer usage a productive experience.
        </p>
    </section>

    <section>
        <hgroup>
            <h3>Our product offerings</h3>
        </hgroup>
        <p>
            Play your favorite music or movies using <i>JustPushPlay</i>.<br />
            <i>PicturePerfect</i> lets you edit your pictures and make them look the way you want to.<br />
            Make movies by putting together images, audio clips and video clips of your choice with <i>MovieMan</i>.<br />
            Reduce the size of large files on your computer with the help of <i>CompressIt</i>.<br />
            Give your computer a nice washdown by just running <i>CleanAll</i>.
        </p>
    </section>

    <section>
        <hgroup>
            <h3>Our project deals</h3>
        </hgroup>
        <p>
            We undertake contracts to build custom software for your computer.
        </p>
    </section>

    <section>
        <hgroup>
            <h3>Our quality assurance</h3>
        </hgroup>
        <p>
            Our products are developed and tested to the highest standards.
        </p>
    </section>
</article>

<aside>
    <h3>Take a look around our product catalog!</h3>
    <p>
        Browse our catalog to look for an app of your interest.
    </p>
</aside>

<aside>
    <h3>Find out about our project contracts!</h3>
    <p>
        If you are interested in getting associated with us, register and let us know in the ContractProposal section.
    </p>
</aside>

SBMS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<section>
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@JelloSoftware.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@JelloSoftware.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@JelloSoftware.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        Jello Software Way<br />
        Syracuse, NY 13210
    </p>
</section>

SBMS/Views/Home/EmployeeLanding.cshtml
@{
    ViewBag.Title = "Employee Portal";
}

<div class="navPortalItem">
    <h3>@Html.ActionLink("Support Requests", "Index", "SupportRequest", null, new { target = "_blank" })</h3>
    <span>Access user submitted support requests</span>
</div>

<br />
<hr />

<div class="navPortalItem">
    <h3>@Html.ActionLink("Contract Proposals", "Index", "ContractProposal", null, new { target = "_blank" })</h3>
    <span>Access user submitted contract proposals</span>
</div>

<div class="navPortalItem">
    <h3>@Html.ActionLink("Query Contract Proposals", "Query", "ScheduleBudgetQuery", null, new { target = "_blank" })</h3>
    <span>Query a contract proposal by username for info about its proposed schedule and budget</span>
</div>

<br />
<hr />

<div class="navPortalItem">
    <h3>@Html.ActionLink("Projects", "Index", "Project", null, new { target = "_blank" })</h3>
    <span>Once a contract proposal is approved, it is added as a project</span>
</div>

<div class="navPortalItem">
    <h3>@Html.ActionLink("Project Issues", "Index", "ProjectIssue", null, new { target = "_blank" })</h3>
    <span>Access employee submitted project issues</span>
</div>

<div class="navPortalItem">
    <h3>@Html.ActionLink("Project Milestones", "Index", "Milestone", null, new { target = "_blank" })</h3>
    <span>Access employee submitted project milestones</span>
</div>

<br />
<hr />

<div class="navPortalItem">
    <h3>@Html.ActionLink("Customers", "Index", "Customer", null, new { target = "_blank" })</h3>
    <span>Once a contract proposal is approved, the user added as a customer</span>
</div>

<div class="navPortalItem">
    <h3>@Html.ActionLink("Customer Issues", "Index", "CustomerIssue", null, new { target = "_blank" })</h3>
    <span>Access employee submitted customer issues</span>
</div>

<br />
<hr />

<div class="navPortalItem">
    <h3>@Html.ActionLink("Meetings And Events", "Index", "MeetingAndEvent", null, new { target = "_blank" })</h3>
    <span>General notes</span>
</div>